'''
Read CGD export of variants and transcript nomenclature (csv) and write out a list of variants (json) 

Created on Jan 18, 2026

@author: pleyte
'''

import argparse
import logging.config
import pandas as pd
from rinc.util.log_config import LogConfig

class CgdCsvToTfxJson(object):
    '''
    Read a csv generated by sql dump, and write out a unique list of variants
    '''
    def __init__(self):
        '''
        Constructor
        '''
        self._logger = logging.getLogger(__name__)
    
    def get_variants(self, input_filename):
        """
        Read a csv containing variants and transcript nomenclature 
        """
        df = pd.read_csv(input_filename, usecols=['genomic_variant', 'chromosome', 'position_start', 'reference_base', 'variant_base']).drop_duplicates()
        self._logger.info(f"Read {df.shape[0]} rows from {input_filename}")
        return df
    
    def write(self, output_filename, variants_df: pd.DataFrame):
        """
        """
        variants_df.rename(columns={'genomic_variant': 'genomicVariantId',
                                    'chromosome': 'chromosome',
                                    'position_start': 'positionStart',
                                    'reference_base': 'referenceBase',
                                    'variant_base': 'variantBase'}, inplace=True)
        variants_df.to_json(output_filename, orient='records', indent=2)
        self._logger.info(f"Wrote {variants_df.shape[0]} rows to {output_filename}")
        
        
def _parse_args():
    parser = argparse.ArgumentParser(description='Convert sql dump to variant list')
    parser.add_argument("--version", action="version", version="0.0.1")
    parser.add_argument("--input", help="SQL dump (csv)", required=True)    
    parser.add_argument("--output", help="Variant list (json)", required=True)
    
    args = parser.parse_args()
    return args    

def main():
    logging.config.dictConfig(LogConfig().stdout_config)

    args = _parse_args()
    
    cgd_to_tfx = CgdCsvToTfxJson()
    variants = cgd_to_tfx.get_variants(args.input)
    cgd_to_tfx.write(args.output, variants)
    
if __name__ == '__main__':
    main()